### ISSUE TITLE
No audio at all

### ISSUE THREAD

**Issue by Pfaeff** [damskaggep/WaveNetVA#7]
Greetings!

This project sounds awesome and I really want to try it. 
I don't seem to get any sound, though. When I press the "Test" button in the "Audio/MIDI Settings" I hear the beep sound and I do see the indicator moving when I play something, but there is no output, even if I turn up the gain all the way. Any idea what could cause this? "Mute audio input" is turned off, of course. 

I do have some cool ideas I want to try with this, but I need to get it working, first 😅 

Thank you very much!

**Comment by ljuvela** [comment]
Which OS are you using, and is this issue happening on the JUCE standalone? On Mac, microphone access for standalone is disabled by default, which prevents getting any input from your audio interface.

You can enable microphone access from Projucer -> Exporters -> Xcode (macOS) -> Microphone Access

Try compiling the VST plugin as well and running it in a DAW. The microphone access issue should only affect the standalone. 
Also remember to compile in Release mode. Debug mode will almost certainly give you buffer grind noises.

**Comment by Pfaeff** [comment]
I am using Windows. The VST seems to work. Microphone access doesn't seem to be an option on Windows. But I'm fine with the VST working. Thank you very much!
